apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: httpd
  name: httpd
  namespace: httpd-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd
  strategy: 
    type: "RollingUpdate"
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - image: anuddeeph/apache-webserver-php
        name: httpd
